### PR TITLE
Migrate to ReScript v11

### PR DESCRIPTION
**Pull request by PascalHonegger**
Hi @johnridesabike , I'm new to ReScript but am trying to learn it to contribute to Coronate 😉 

Because Coronate depends on this library, I frist tried to migrate it to the latest v11, but the changes are quite breaking.

What I did:
- Config changes in rescript.json based on what I believe to be best practices
- Replace Js. module with @rescript/core
- Adjust code for new uncurried mode (as best as I understand)

There are a few open points I would be happy to get some input from you:

- I would also remove the commonjs package and enable in-source for esmodule, but maybe that's too breaking?
- I was not able to get the `isEmpty` and `has` method to compile due to some currying-problems with the new uncurry mode
- The documentation module seems very outdated, no idea if it still works of if a modern alternative exists

### CODE REVIEW

**Comment by johnridesabike** [comment]
Cool, thanks for your interest in updating this! It's been a long time since I last looked at this code, but here are my thoughts on your questions:

1. I think I used both commonjs and esmodule because that was an easy way to run benchmarks and tests in different environments (i.e., Node.js and a browser) without using a bundler. I don't feel strongly about changing it, assuming the tests still work.
2. I'm not on a computer where I can build the repo to test it myself, but I think you might be able to fix `isEmpty` and `has` by defining them as new functions which call their corresponding `Belt` functions, e.g.: 
`let isEmpty = x => Belt.Map.isEmpty(x)`
3. The documentation was kind of experimental and fragile, and honestly I don't have much of an interest in maintaining it at this point. I'm happy to remove it and simply refer to the README and the .resi file for documentation.

Some other thoughts:

The algorithm implemented in this repo was intended to be a pure-ReScript replacement for this npm package: https://www.npmjs.com/package/edmonds-blossom. I think I waaay over-engineered it, though, and if I had to do it again I would just write bindings to the original npm package. But as long as it continues to work without too much maintenance, I'm happy to keep it up.

**Comment by PascalHonegger** [comment]
Thanks for your feedback, indeed implementing the methods did the trick to get it compiling 😄 

I also did some more tweaking here and there but nothing major. The benchmark.js tool used is quite ancient but I also found no drop-in replacement so I kept the CommonJS build. I switched the unit tests to fully run in the (still experimental) ESM mode from jest, which seems to work fine on my machine. I was not able to get the browser benchmark working though, I also deleted the docs for now but the readme might need some update.

Once you have time you can take a look and add any comments you see fit!

**Comment by johnridesabike** [comment]
Could you add a changelog entry? Just add a version 4.0 with the notes saying it uses ReScript 11. Besides that, it looks good to me.

**Comment by PascalHonegger** [comment]
> Could you add a changelog entry? Just add a version 4.0 with the notes saying it uses ReScript 11. Besides that, it looks good to me.

Added a changelog entry 👍

**Comment by johnridesabike** [comment]
Looks good to me! I also updated the npm package with the new version.

**Pull request merged**
